from decimal import Decimal
from django.db import models
from django.conf import settings
from django.core.validators import MinValueValidator
from apps.doctors.models import Doctor


#sql:
# CREATE TABLE "doctors_appointmentslot" (
#     "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
#     "starts_at" timestamp with time zone NOT NULL,
#     "is_active" boolean NOT NULL DEFAULT TRUE,
#     "created_at" timestamp with time zone NOT NULL,
#     "doctor_id" bigint NOT NULL REFERENCES "doctors_doctor" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
# );
class AppointmentSlot(models.Model):
    doctor = models.ForeignKey(
        Doctor,
        on_delete=models.CASCADE,
        related_name="slots",
        verbose_name="Doctor",
    )
    starts_at = models.DateTimeField(
        verbose_name="Starts At",
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name="Is Active",
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Created At",
    )

    class Meta:
        verbose_name = "Appointment Slot"
        verbose_name_plural = "Appointment Slots"
        #ORDER BY "starts_at" ASC
        ordering = ["starts_at"]
        #Optimization for usual query:  AppointmentSlot.objects.filter(doctor_id=5, starts_at__gte=now())
        #show doctor appointments for specific time

        indexes = [
            models.Index(fields=["doctor", "starts_at"]),
        ]
        #prevent douplication for one doctor has two same time slot==>IntegrityError
        constraints = [
            models.UniqueConstraint(
                fields=["doctor", "starts_at"],
                name="unique_slot_per_doctor_time",
            )
        ]

    def __str__(self):
        return f"{self.doctor} @ {self.starts_at}"

class Appointment(models.Model):
    class Status(models.TextChoices):
        CONFIRMED = "CONFIRMED", "Confirmed"
        COMPLETED = "COMPLETED", "Completed"

    patient = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.PROTECT,
        related_name="appointments",
        #patient.appointments.all()
        verbose_name="Patient",
    )
    slot = models.OneToOneField(
        AppointmentSlot,
        on_delete=models.PROTECT,
        related_name="appointment",
        #slot.appointment==>find slot from appointment
        verbose_name="Slot",
    )
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.CONFIRMED,
        verbose_name="Status",
    )
    amount_paid = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        validators=[MinValueValidator(Decimal("0.00"))],
        verbose_name="Amount Paid",
    )
    booked_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Booked At",
    )
    completed_at = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name="Completed At",
    )
    completed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        #user.completed_appointments.all()
        related_name="completed_appointments",
        verbose_name="Completed By",
    )

    class Meta:
        verbose_name = "Appointment"
        verbose_name_plural = "Appointments"
        ordering = ["-booked_at"]
        indexes = [
            models.Index(fields=["patient", "status"]),
        ]
        constraints = [
            models.CheckConstraint(
                condition=models.Q(amount_paid__gte=0),
                name="appointment_amount_paid_gte_zero",
            )
        ]

    def __str__(self):
        return f"Appointment #{self.id} - {self.patient}"
