# Generated by Django 5.2.17 on 2026-09-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                verbose_name="Amount paid",
            ),
        ),
    ]
